
stages:
    - build
    - test
    - deploy

build-project:
  stage: build
  script:
    - cp -r * $BUILDS_DIRECTORY
    - cd $BUILDS_DIRECTORY
    - mvn clean install
    - cd $SOURCE_DIR
    - tar -zcvf  $CI_PROJECT_DIR/$BUILD_ARTIFACT_FILE_NAME $CI_PROJECT_DIR/target
    - echo $CI_PROJECT_DIR
  artifacts:
    paths:
      - $CI_PROJECT_DIR/$BUILD_ARTIFACT_FILE_NAME
    # - echo "Running Jobs with Username:"
    # - whoami
    # - chmod +x ./deploy.sh
    # - git config --global --add safe.directory $SOURCE_DIR/$SOURCE_REPO
    # - git config --global --add safe.directory $DEPLOY_DIR/$DEPLOY_REPO
    # - ./deploy.sh
  tags:
    - ugrad
  only:
    - master
    - staging
    - development

test-build:
  stage: test
  script:
    - echo "Triggerring Tests"
    - cd $BUILDS_DIRECTORY
    - mvn clean test
    - echo "Tests Successful"
  tags:
    - ugrad
  only:
    - master
    - staging

deploy-build:
  stage: deploy
  script:
    - echo "Triggerring Deploy"
    - echo "Deploy Complete"
  tags:
    - ugrad
  only:
    - master
