# This YAML file demonstrates building a gradle console app and deploying it to your
# Timberlea account via secure copy.

# NOTE: It does not upload your test results to GitLab, you will need
# to figure that out still.

# NOTE: You will need to adjust the following variable to the build output of your app
#       right now it's configured to deploy an Android APK file from another class I taught.
variables:
  EXECUTABLE_TO_DEPLOY: "app/build/outputs/apk/debug/app-debug.apk"
  DESTINATION_FILE: "App-${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}.apk"

before_script:
  # The following line is only necessary if using a docker-based runner.
  #- apk add --no-cache openssh-client
  - chmod +x ./gradlew

stages:
  - build
  - test
  - deploy

assembleDebug:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/
  tags:
    - ugrad

debugTests:
  stage: test
  script:
    - ./gradlew -Pci --console=plain :app:testDebug
  tags:
    - ugrad
    
deployJob:
  stage: deploy
  tags:
    - ugrad
  artifacts:
    paths:
      - app/build/outputs
  script:
    - chmod og-rwx ${DEPLOY_SSH_KEY}
    - scp -r -o StrictHostKeyChecking=no -i "${DEPLOY_SSH_KEY}" ${EXECUTABLE_TO_DEPLOY} "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${DESTINATION_FILE}"
