stages:
  - build
  - test
  - deploy

image: maven:latest

variables:
  GIT_STRATEGY: clone

build-group2:
  stage: build
  tags:
    - dalfcs_docker_kvm
  script: mvn clean compile
  only:
    - master
    - staging
    - development


test-group2:
  stage: test
  tags:
    - dalfcs_docker_kvm
  script: mvn clean test
  only:
    - master
    - staging

deploy-group2:
  stage: deploy
  tags:
    - dalfcs_docker_kvm
  image: ruby:2.6
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APPLICATION_NAME --api-key=$HEROKU_API_KEY
  only:
    - master
    - staging