build-job:
  stage: build
  script:
    - BUILD_DIRECTORY=$SOURCE_DIR/builds
    - mkdir -p $BUILD_DIRECTORY
    - cp -r * $BUILD_DIRECTORY
    - cd $SOURCE_DIR
    - rm -rf deploy.sh LICENSE mvnw Procfile src/main/ system.properties README.md docs/ pom.xml app.json
    - echo "Building and Deploying to Heroku"
    # - echo "Running Jobs with Username:"
    # - whoami
    # - chmod +x ./deploy.sh
    # - git config --global --add safe.directory $SOURCE_DIR/$SOURCE_REPO
    # - git config --global --add safe.directory $DEPLOY_DIR/$DEPLOY_REPO
    # - ./deploy.sh
  tags:
    - ugrad

# test-job1:
#   stage: test
#   script:
#     - echo "This job tests something"
#   tags:
#     - ugrad

# test-job2:
#   stage: test
#   script:
#     - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
#     - echo "This job tests something, but takes more time than test-job1."
#     - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
#     - echo "which simulates a test that runs 20 seconds longer than test-job1"
#     - sleep 20
#   tags:
#     - ugrad

# deploy-prod:
#   stage: deploy
#   script:
#     - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
#   tags:
#     - ugrad
